config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, except: :index
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.valid? #valid?によって、@postが正しく保存されるものなのかどうかを判断している。保存されるようであれば保存しルートパスへ。保存できないものであれば、新規投稿ページに戻っている
      @post.save

      redirect_to root_path

    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.valid? #valid?によって、@postが正しく更新されるものなのかどうかを判断している。更新されるものであれば詳細ページに戻り、更新できないものであれば、投稿編集ページに戻っている
      redirect_to post_path(@post.id)
    else
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ourblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__title">
        <%= link_to "Our Blog", root_path , class: "header__title--text" %>
      </div>
      </div>
      <div class="header__right">
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
          <%= link_to "新規投稿", new_post_path, class: "header__right--btn" %>
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "header__right--btn" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
      </div>
    </header>
    <div class="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_error_messages.html.erb
<% if post.errors.any? %>
  <div id="error_explanation">
    <b>エラーです</b>
    <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="content">
  <div class="content__left">
    <div class="content__left--image"></div>
  </div>
  <div class="content__right">
    <div class="content__right__top">
      <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
    </div>
    <div class="content__right__bottom">
      <div class="content__right__bottom--userName">
        <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %>
      </div>
      <div class="content__right__bottom--date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="content__title">
  投稿の編集
</div>
<%= render partial: "error_messages", locals: { post: @post } %>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
<% end %>

app/views/posts/new.html.erb
<div class="content__title">
  新規記事の作成
</div>
<%= render partial: "error_messages", locals: { post: @post } %>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/show.html.erb
<div class="postTitle">
  <%= @post.title %>
</div>
<div class="postDate">
  <%= @post.created_at %>
</div>
<div class="postAuthor">
</div>
<div class="postManage">
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "編集", edit_post_path(@post.id), class: "postManage__edit" %>
    <%= link_to "削除", post_path(@post.id), data: { turbo_method: :delete }, class: "postManage__delete" %>
  <% end %>
</div>
<div class="postText">
  <%= simple_format @post.content %>
</div>

app/views/users/show.html.erb
<div class="postTitle">
  <%= @user.nickname %>さんの投稿一覧
</div>
<% @posts.each do |post| %>
  <%= render partial: "posts/post", locals: { post: post } %>
<% end %>